param([switch]$Get)

'3D Objects'
'AccountPictures'
if ($Get) { 'AddNewProgramsFolder' }
'Administrative Tools'
'AppData'
'AppDataDesktop'
'AppDataDocuments'
'AppDataFavorites'
'AppDataProgramData'
'Application Shortcuts'
'AppMods'
if ($Get) { 'AppsFolder' }
if ($Get) { 'AppUpdatesFolder' }
'Cache'
'Camera Roll'
'CameraRollLibrary'
'Captures'
'CDBurning'
'Common Administrative Tools'
'Common Desktop'
'Common Documents'
'Common Programs'
'Common Start Menu'
'Common Start Menu Places'
'Common Startup'
'Common Templates'
'CommonDownloads'
'CommonMusic'
'CommonPictures'
'CommonRingtones'
'CommonVideo'
if ($Get) { 'ConflictFolder' }
if ($Get) { 'ConnectionsFolder' }
'Contacts'
if ($Get) { 'ControlPanelFolder' }
'Cookies'
'CredentialManager'
'CryptoKeys'
if ($Get) { 'CSCFolder' }
'DesktopFolder'
'Development Files'
'Device Metadata Store'
'DocumentsLibrary'
'Downloads'
'DpapiKeys'
'Favorites'
'Fonts'
'GameTasks'
'History'
if ($Get) { 'HomeGroupFolder' }
'ImplicitAppShortcuts'
'Libraries'
'Links'
'LocalAppData'
'LocalAppDataLow'
'LocalizedResourcesDir'
'MusicLibrary'
'My Documents'
'My Music'
'My Pictures'
'My Video'
if ($Get) { 'MyComputerFolder' }
'NetHood'
if ($Get) { 'NetworkPlacesFolder' }
'OEM Links'
'OneDrive'
'OneDriveCameraRoll'
'OneDriveDocuments'
'OneDriveMusic'
'OneDrivePictures'
'Original Images'
'PhotoAlbums'
'PicturesLibrary'
'Playlists'
if ($Get) { 'PrintersFolder' }
'PrintHood'
'Profile'
'ProgramData'
'ProgramFiles'
'ProgramFilesCommon'
'ProgramFilesCommonX86'
'ProgramFilesX86'
'Programs'
'Public'
'PublicAccountPictures'
'PublicGameTasks'
'PublicLibraries'
'Quick Launch'
'Recent'
'Recorded Calls'
'RecordedTVLibrary'
if ($Get) { 'RecycleBinFolder' }
'ResourceDir'
'RetailDemo'
'Ringtones'
'Roamed Tile Images'
'Roaming Tiles'
'SampleMusic'
'SamplePictures'
'SampleVideos'
'SavedGames'
'SavedPictures'
'SavedPicturesLibrary'
'Screenshots'
'Searches'
'SearchHistoryFolder'
if ($Get) { 'SearchHomeFolder' }
'SearchTemplatesFolder'
'SendTo'
'Start Menu'
'Startup'
if ($Get) { 'SyncCenterFolder' }
if ($Get) { 'SyncResultsFolder' }
if ($Get) { 'SyncSetupFolder' }
'System'
'SystemCertificates'
'SystemX86'
'Templates'
'User Pinned'
'UserProfiles'
'UserProgramFiles'
'UserProgramFilesCommon'
'VideosLibrary'
'Windows'
